[phases.setup]
nixPkgs = ["python311", "nodejs", "chromium"]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt",
  "python3 -m playwright install --with-deps"
]

[phases.build]
cmds = [
  "echo 'Build completed'"
]

[start]
cmd = "python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT"
